apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lyy331t26-nodejs
  janus-idp.io/tekton: lyy331t26-nodejs
  backstage.io/kubernetes-id: lyy331t26-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: lyy331t26-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
